# Generated by Django 2.2.6 on 2019-11-05 19:25

from django.db import migrations
from django.conf import settings
from django.utils import timezone


def migrate_forward(apps, schema_editor):
    TadoSettings = apps.get_model('dsmr_tado', 'TadoSettings')
    ScheduledProcess = apps.get_model('dsmr_backend', 'ScheduledProcess')

    app_settings, _ = TadoSettings.objects.get_or_create()  # Ensure we have at least an instance.

    ScheduledProcess.objects.create(
        name='Tado update',
        module=settings.DSMRREADER_MODULE_TADO_UPDATE,
        active=app_settings.track,
        planned=app_settings.next_sync or timezone.now(),
    )


def migrate_backward(apps, schema_editor):
    ScheduledProcess = apps.get_model('dsmr_backend', 'ScheduledProcess')
    ScheduledProcess.objects.filter(module=settings.DSMRREADER_MODULE_TADO_UPDATE).delete()


class Migration(migrations.Migration):

    operations = [
        migrations.RunPython(migrate_forward, migrate_backward),
        migrations.RemoveField(
            model_name='tadosettings',
            name='next_sync',
        ),
    ]

    dependencies = [
        ('dsmr_tado', '0005_tado_refactor_scheduling'),
    ]
